name: mere_maahi_dummy
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  build_runner: ^2.4.6
  cached_network_image: ^3.3.1
  calendar_date_picker2: ^0.5.3
  card_swiper: ^3.0.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.17.3
  connectivity_plus: ^5.0.2
  country_state_city_picker: ^1.2.8
  csc_picker: ^0.2.7
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.5.0+1
  firebase_auth: ^4.17.4
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.3
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_card_swiper: ^7.0.0
  flutter_local_notifications: ^17.1.2
  flutter_login_facebook: ^1.6.2
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.7.0
  form_validator: ^2.1.1
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  google_sign_in: ^5.0.7
  image_picker: ^1.0.7
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  intl_phone_number_input: ^0.7.4
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1
  one_context: ^2.1.0
  photo_view: ^0.14.0
  pin_code_fields: ^8.0.1
  pinput: ^4.0.0
  readmore: ^2.2.0
  rxdart: ^0.27.7
  scaffold_gradient_background: ^1.0.3+1
  shared_preferences: ^2.2.2
  simple_gradient_text: ^1.3.0
  smooth_page_indicator: ^1.1.0
  sms_autofill: ^2.3.0
  telephony: ^0.2.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
